services:
  - type: web
    name: maikito-san-backend
    env: python
    branch: master
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python start_smart.py"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
        value: AIzaSyDLQ4bW0sG0_JGfhVCaTU8nzH2HpcBVY6c
